=== mobilist/phloem/etc/node.dtd
<!--

 Copyright (C) 2009 Simon Dawson

 This file is part of Phloem.

    Phloem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Phloem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Phloem.  If not, see <http://www.gnu.org/licenses/>.

-->

<!ELEMENT node (root, rsync, role+, description?)>
<!ATTLIST node
  id       ID     #REQUIRED
  group    CDATA  #IMPLIED
  is_root  (0|1)  "0"
  host     CDATA  #IMPLIED
>

<!ELEMENT root EMPTY>
<!ATTLIST root
  host  CDATA  #REQUIRED
  port  CDATA  #REQUIRED
>

<!ELEMENT rsync EMPTY>
<!ATTLIST rsync
  user  CDATA  #REQUIRED
>

<!-- N.B. Ideally, only roles of type subscribe should be allowed to define a
     filter... -->
<!ELEMENT role (directory, filter?, description?)>
<!ATTLIST role
  type    (publish|subscribe)    #REQUIRED
  route   (rootward|leafward)  #REQUIRED
  active  (0|1)  "1"
>

<!ELEMENT description (#PCDATA)>

<!ELEMENT directory EMPTY>
<!ATTLIST directory
  path  CDATA  #REQUIRED
>

<!ELEMENT filter EMPTY>
<!ATTLIST filter
  type   (node|group)   #REQUIRED
  value  CDATA          #REQUIRED
  rule   (match|exact)  "exact"
>

=== mobilist/phloem/t/data/testroot.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE node SYSTEM "node.dtd">

<!--

 Copyright (C) 2009-2010 Simon Dawson

 This file is part of Phloem.

    Phloem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Phloem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Phloem.  If not, see <http://www.gnu.org/licenses/>.

-->

<node id="testroot" group="testers" is_root="1" host="10.127.10.4">

  <description>
    This is a dummy root node, for testing purposes.
  </description>

  <root host="10.127.10.4" port="9999" />

  <rsync user="simond"
    ssh_id_file="etc/.ssh/id_rsa"
    ssh_port="22" />

  <role type="publish" route="root2leaf">
    <directory path="/home/simond/Projects/Personal/svn/phloem/testroot/root2leaf/" />
    <description>
      Publish root2leaf content.
    </description>
  </role>

  <role type="subscribe" route="leaf2root" active="1">
    <directory path="/home/simond/Projects/Personal/svn/phloem/testroot/leaf2root/" />
    <filter type="node" value="^test\w+" rule="match" />
    <description>
      Subscribe to leaf2root content from matching publisher nodes.
    </description>
  </role>

</node>

=== mobilist/phloem/etc/node.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE node SYSTEM "node.dtd">

<!--

 Copyright (C) 2009 Simon Dawson

 This file is part of Phloem.

    Phloem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Phloem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Phloem.  If not, see <http://www.gnu.org/licenses/>.

-->

<node id="egg12345" group="eggs" is_root="1" host="localhost"
  register_frequency_s="15">

  <description>
    This is just a dummy node, for testing purposes.
  </description>

  <root host="localhost" port="9999" />

  <rsync user="simond" ssh_id_file="etc/.ssh/id_rsa" />

  <role type="publish" route="root2leaf">
    <directory path="/some/path" />
    <description>
      Publish root2leaf content.
    </description>
  </role>

  <role type="publish" route="leaf2root" active="0">
    <directory path="/some/other/path" />
    <description>
      Publish leaf2root content. Currently disabled.
    </description>
  </role>

  <role type="subscribe" route="root2leaf" update_frequency_s="10">
    <directory path="/a/path" />
    <filter type="group" value="^egg\w+" rule="match" />
    <description>
      Subscribe to root2leaf content from matching publisher nodes.
    </description>
  </role>

  <role type="subscribe" route="leaf2root" update_frequency_s="5"
    active="0">
    <directory path="/another/path" />
    <description>
      Subscribe to leaf2root content from any publisher node.
      Currently disabled.
    </description>
  </role>

</node>

=== mobilist/phloem/t/data/testleaf.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE node SYSTEM "node.dtd">

<!--

 Copyright (C) 2009 Simon Dawson

 This file is part of Phloem.

    Phloem is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Phloem is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Phloem.  If not, see <http://www.gnu.org/licenses/>.

-->

<node id="testleaf" group="testers" is_root="0" host="10.127.10.4">

  <description>
    This is a dummy leaf node, for testing purposes.
  </description>

  <root host="10.127.10.4" port="9999" />

  <rsync user="simond" />

  <role type="publish" route="leaf2root">
    <directory path="/home/simond/Projects/svn/phloem/testleaf/leaf2root/" />
    <description>
      Publish leaf2root content.
    </description>
  </role>

  <role type="subscribe" route="root2leaf" active="1">
    <directory path="/home/simond/Projects/svn/phloem/testleaf/root2leaf/" />
    <filter type="group" value="^test\w+" rule="match" />
    <description>
      Subscribe to root2leaf content from matching publisher nodes.
    </description>
  </role>

</node>
